#!/bin/bash

echo "=== ATR3 Backend Email Setup ==="
echo ""
echo "To enable email notifications, you need to:"
echo "1. Create a Gmail app password"
echo "2. Set environment variables"
echo ""
echo "Steps to create Gmail app password:"
echo "1. Go to: https://myaccount.google.com/"
echo "2. Security → 2-Step Verification (enable if needed)"
echo "3. App passwords → Generate new password for 'Mail'"
echo "4. Copy the 16-character password"
echo ""
echo "Enter your Gmail address:"
read GMAIL_USER
echo ""
echo "Enter your Gmail app password (16 characters):"
read -s GMAIL_PASS
echo ""
echo ""
echo "Setting environment variables..."
export GMAIL_USER="$GMAIL_USER"
export GMAIL_PASS="$GMAIL_PASS"
echo "Environment variables set!"
echo ""
echo "To start the server with email enabled, run:"
echo "cd backend && GMAIL_USER='$GMAIL_USER' GMAIL_PASS='$GMAIL_PASS' node index.js"
echo ""
echo "Or add these to your ~/.bashrc file for permanent setup:"
echo "export GMAIL_USER='$GMAIL_USER'"
echo "export GMAIL_PASS='$GMAIL_PASS'" 